#!/bin/sh
cp ./terminus.c.in ./terminus.c
for I in `find ./src/lib -name "terminus.h" -print`; do
  cat $I >> ./terminus.c
done
#for I in `find ./src/lib -name "*.c" -print`; do
#  cat $I >> ./terminus.c
#done
rm -rf ./doc/html ./doc/latex ./doc/man
doxygen
cp doc/img/*.png doc/html/
exit 0
