#!/bin/sh                                                                                       

PID="us.ryanhope.terminus"

if [ -z "$IPKG_OFFLINE_ROOT" ]; then
  IPKG_OFFLINE_ROOT=/media/cryptofs/apps
fi

# Install the upstart script
rm -f /etc/event.d/${PID}
cp $IPKG_OFFLINE_ROOT/etc/event.d/${PID} /etc/event.d/${PID}

exit 0
